### ISSUE TITLE
Syntax incompatibility with GHC

### ISSUE THREAD

**Issue by FranklinChen** [seanparsons/haskellscript#1]
Is there a reason you chose `--#` directive that happens to be incompatible with GHC comment syntax, so that a source file with that directive cannot be used directly with GHC?

**Comment by seanparsons** [comment]
It was mostly chosen arbitrarily if I'm honest, didn't even know it would break GHC!

**Comment by seanparsons** [comment]
Seems that any symbol immediately after any number of hyphens (from my quick experimenting in GHCi) is incompatible, which is....Less than helpful.

**Comment by FranklinChen** [comment]
Yes. I'd suggest changing the directive so that it's a legal comment, maybe by adding a space.
